services:
  apache:
    container_name: apache_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/
    networks:
      - dev
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db_maria
      MARIADB_USER: root
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "6033:3306"
    networks:
      - dev

volumes:
  db-data:

networks:
  dev:
    driver: bridge